project:
  type: website

website:
  title: "jordieb"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/JordieB
      - icon: twitter
        href: https://twitter.com/JayArrArrBee
format:
  html:
    theme: cosmo
    css: styles.css
